[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace STM32F429ZITx with your chip as listed in `probe-rs chip list`
# runner = "probe-rs run --chip STM32F429ZITx"
# runner = "JLinkExe -device STM32F401RE -autoconnect 1 -if SWD -speed 4000 -CommanderScript JLinkScript.jlink"
[build]
# target = "arm-none-eabi"
# v7是cortex系列？
target = "thumbv7em-none-eabi"

[env]
DEFMT_LOG = "trace"
