[package]
name = "stage3"
version = "0.1.0"
authors = ["Yifan Wu <shinbokuow@163.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# 在这里列出你的项目依赖

[profile.release]
# 在这里配置你的发布配置
